	.code64
	.section .text
	.global _start

	/* physical addresses generated by the bootloader */
	.equ ZERO_PAGE, 0x90000
	.equ CMDLINE_DST, 0X20000
	.equ ROOTFS_DST, 0x4000000
	.equ VMLINUZ_DST, 0x1000000

	.ifndef ROOTFS_SIZE_BYTES
	.equ ROOTFS_SIZE_BYTES, 0x02000000
	.endif

_start:
	mov $0x10, %ax
	mov %ax, %ds
	mov %ax, %es
	mov %ax, %fs
	mov %ax, %gs
	mov %ax, %ss
	mov $0x500000, %rsp

	mov $ZERO_PAGE, %rdi
	xor %rax, %rax
	mov $512, %rcx
	rep stosq

	mov $ZERO_PAGE, %rbx
	movl $0x53726448, 0x202(%rbx)
	movw $0x020F, 0x206(%rbx)
	movb $0xFF, 0x210(%rbx)

	movl $ROOTFS_DST, 0x218(%rbx)
	movl $ROOTFS_SIZE_BYTES, 0x21C(%rbx)

	lea kernel_cmdline(%rip), %rsi
	mov $CMDLINE_DST, %rdi
.copy_loop:
	lodsb
	stosb
	test %al, %al
	jnz .copy_loop

	movl $CMDLINE_DST, 0x228(%rbx)
	mov $ZERO_PAGE, %rsi

	mov $VMLINUZ_DST, %rax
	add $0x200, %rax
	jmp *%rax

	.section .rodata

kernel_cmdline:
	.asciz "root=/dev/ram0 rw rdinit=/sbin/init console=tty0 quiet loglevel=3"
